sugarcube-2:
  macros:
    actions-add:
      name: actions-add
      parameters: ["link"]
    actions-get:
      name: actions-get
      parameters: ['']
    actions-optional:
      name: actions-optional
      parameters: ['text']
    archive-barbs:
      name: archive-barbs
      parameters: ["bareword &+ boolean &+ boolean"]
    archive-ending:
      name: archive-ending
      children: ["archive-variants"]
      container: true
      parameters: ["boolean &+ link|text |+ text"]
    archive-option:
      name: archive-option
      paramters: ["text &+ text &+ boolean"]
    archive-variant:
      name: archive-variant
      children: ["archive-option"]
      container: true
      parameters: ["text &+ text"]
    archive-variants:
      name: archive-variants
      parameters: []
    arousalbar:
      name: arousalbar
    barbs-announce:
      name: barbs-announce
      parameters: ["'now'|'soon'|'maybe'"]
    big-mood:
      name: big-mood
      parameters:
        - "(bareword|var) &+ ( 'ignore'|'TODO'|'vary' )"
        - "(bareword|var) &+ ( 'always'|'assert'|'implies' ) &+ ...text"
    em-assert:
      name: em-assert
    em-fail:
      name: em-fail
    expand-ignore:
      name: expand-ignore
      parameters: ['text |+ ...text']
    fade-in:
      name: fade-in
      children: ['fade-next']
      container: true
      parameters: ['bareword']
    fade-next:
      name: fade-next
      parameters: ['bareword']
    glitch-text:
      name: glitch-text
      container: true
    meta-ending:
      name: meta-ending
      parameters: ['("bad"|"good") &+ bareword &+ text |+ bareword &+ text']
    misfire-password:
      name: misfire-password
      paramaters: ['text']
    misfire-please:
      name: misfire-please
      container: true
      parameters: ['']
    n1-no-loop:
      name: n1-no-loop
      parameters: ['link']
    n1-patience:
      name: n1-patience
      parameters: ['number &+ number &+ text |+ text |+ text']
    pw-another:
      name: pw-another
      parameters: ['text |+ text']
    pw-choice:
      name: pw-choice
      children: ['pw-another', 'pw-fail']
      container: true
      parameters: ['text |+ text']
    pw-fail:
      name: pw-fail
    revisit-here:
      name: revisit-here
    sidebar-auto-stow:
      name: sidebar-auto-stow
      paramters: ['']
    state-delete:
      name: state-delete
      parameters: ['bareword |+ ...bareword']
    state-load:
      name: state-load
      parameters: ['bareword']
    state-save:
      name: state-save
      parameters: ['bareword &+ ...bareword']
    "TOD\x4f":
      name: "TOD\x4f"
    var-trace-ignore:
      name: var-trace-ignore
      container: true
      parameters: ['']

