sugarcube-2:
  macros:
    act:
      name: act
      container: true
      parameters: ["text|link"]
    arc-barbs:
      name: arc-barbs
      parameters: ["bareword"]
    arc-ending:
      name: arc-ending
      container: true
      children: ["arc-variants"]
      parameters: ["boolean &+ link|text |+ text |+ text"]
    arc-only:
      name: arc-only
      container: true
      parameters: [""]
    arc-option:
      name: arc-option
      parameters: ["text &+ text &+ boolean"]
    arc-set-barbs:
      name: arc-set-barbs
      parameters: ["bareword"]
    arc-skip:
      name: arc-skip
      container: true
      parameters: [""]
    arc-select:
      name: arc-select
      container: true
      children: ["arc-option"]
      parameters: ["text &+ text"]
    arc-variants:
      name: arc-variants
      parameters: [""]
    arousal-bar:
      name: arousal-bar
      parameters: ["number &+ number &+ ('weak'|'strong'|'max')"]
    barbs-announce:
      name: barbs-announce
      parameters: ["'now'|'soon'|'maybe'"]
    checkpoint-action:
      name: checkpoint-action
      parameters: ["bareword"]
    checkpoint-load:
      name: checkpoint-load
      parameters: ["bareword"]
    checkpoint-save:
      name: checkpoint-save
      parameters: ["bareword &+ text"]
    cv-ignore:
      name: cv-ignore
      parameters: ["bareword |+ ...bareword"]
    cv-try:
      name: cv-try
      parameters: ["bareword &+ text |+ ...text"]
    em-assert:
      name: em-assert
    ending-bad:
      name: ending-bad
      parameters: ["text |+ bareword"]
    ending-challenge:
      name: ending-challenge
      parameters: ["text |+ bareword"]
    ending-good:
      name: ending-good
      parameters: ["text |+ bareword"]
    em-fail:
      name: em-fail
    fade-in:
      name: fade-in
      container: true
      children: ["fade-next"]
      parameters: ["text |+ ...('click-anywhere'|'no-dots'|'no-pulse')"]
    fade-next:
      name: fade-next
      parameters: ["text"]
    kw-announce:
      name: kw-announce
      parameters: [""]
    kw-unlock-soon:
      name: kw-unlock-soon
      parameters: ["bareword"]
    glitch-text:
      name: glitch-text
      container: true
      parameters: ["|+ number"]
    mf-else:
      name: mf-else
      parameters: []
    mf-pass:
      name: mf-pass
      container: true
      children: ["mf-else"]
      parameters: ["text"]
    mf-please:
      name: mf-please
      container: true
      parameters: [""]
    mt-seen:
      name: mt-seen
      container: true
      parameters: ["text |+ ...text"]
    mta:
      name: mta
      container: true
      parameters: ["(text|link) |+ text"]
    mta-no-loop:
      name: mta-no-loop
      container: true
      parameters: ["link|text"]
    mtl:
      name: mtl
      container: true
      parameters: ["(text|link) |+ text"]
    mtl-denied:
      name: mtl-denied
      parameters: ["text |+ text"]
    mtl-if:
      name: mtl-if
      container: true
      parameters: ["text &+ (text|link) |+ text"]
    n1-patience:
      name: n1-patience
      container: true
      children: ["n1-remind", "n1-repeat", "n1-warn", "n1-insist"]
      parameters: ["number &+ number"]
    n1-insist:
      name: n1-insist
      parameters: [""]
    n1-remind:
      name: n1-remind
      parameters: [""]
    n1-repeat:
      name: n1-repeat
      parameters: [""]
    n1-warn:
      name: n1-warn
      parameters: [""]
    nero-caged:
      name: nero-caged
      container: true
      children: ["nero-caged-fill"]
      parameters: ["link"]
    nero-caged-fill:
      name: nero-caged-fill
      parameters: [""]
    pw-another:
      name: pw-another
      parameters: ["text"]
    pw-fail:
      name: pw-fail
      parameters: [""]
    pw-found:
      name: pw-found
      parameters: ["text"]
    pw-suggest:
      name: pw-suggest
      container: true
      children: ["pw-another", "pw-fail"]
      parameters: ["text"]
    random-once:
      name: random-once
      children: ["ro-choice"]
      container: true
      parameters: ["bareword"]
    return-before:
      name: return-before
      parameters: ["link|text"]
    ro-choice:
      name: ro-choice
      parameters: ["|+ text"]
    revisit-here:
      name: revisit-here
    sticky-head:
      name: sticky-head
      container: true
      parameters: [""]
    sticky-return:
      name: sticky-return
      parameters: [""]
    sticky-return-and:
      name: sticky-return-and
      container: true
      parameters: [""]
    tran-cut:
      name: tran-cut
      parameters: ["link", "text &+ (text|link)"]
    tran-cut-span:
      name: tran-cut-span
      container: true
      parameters: [""]
    vi-always:
      name: vi-always
      parameters: ["bareword &+ text |+ ...text"]
    vi-always-if:
      name: vi-always-if
      parameters: ["bareword &+ bareword &+ text |+ ...text"]
    vi-ignore:
      name: vi-ignore
      parameters: ["bareword |+ ...bareword"]
    vi-ignore-if:
      name: vi-ignore-if
      parameters: ["bareword &+ ...bareword"]


