sugarcube-2:
  macros:
    actions-add:
      name: actions-add
      parameters: ["link"]
    actions-get:
      name: actions-get
      parameters: [""]
    actions-optional:
      name: actions-optional
      parameters: ["text"]
    archive-barbs:
      name: archive-barbs
      parameters: ["bareword &+ boolean &+ boolean"]
    archive-ending:
      name: archive-ending
      container: true
      children: ["archive-variants"]
      parameters: ["boolean &+ link|text |+ text"]
    archive-option:
      name: archive-option
      paramters: ["text &+ text &+ boolean"]
    archive-variant:
      name: archive-variant
      container: true
      children: ["archive-option"]
      parameters: ["text &+ text"]
    archive-variants:
      name: archive-variants
      parameters: [""]
    arousalbar:
      name: arousalbar
    auto-stow:
      name: auto-stow
      parameters: [""]
    barbs-announce:
      name: barbs-announce
      parameters: ["'now'|'soon'|'maybe'"]
    cv-ignore:
      name: cv-ignore
      parameters: ["bareword |+ ...bareword"]
    cv-try:
      name: cv-try
      parameters: ["bareword &+ text |+ ...text"]
    em-assert:
      name: em-assert
    em-fail:
      name: em-fail
    fade-in:
      name: fade-in
      container: true
      children: ["fade-next"]
      parameters: ["bareword"]
    fade-next:
      name: fade-next
      parameters: ["bareword"]
    glitch-text:
      name: glitch-text
      container: true
      parameters: ["|+ number"]
    meta-ending:
      name: meta-ending
      parameters: ["('bad'|'good') &+ bareword &+ text |+ bareword &+ text"]
    misfire-please:
      name: misfire-please
      container: true
      parameters: [""]
    mtl:
      name: mtl
      container: true
      parameters: ["(text|link) |+ text"]
    n1-no-loop:
      name: n1-no-loop
      parameters: ["link"]
    n1-patience:
      name: n1-patience
      container: true
      children: ["n1-remind", "n1-repeat", "n1-warn", "n1-insist"]
      parameters: ["number &+ number"]
    n1-insist:
      name: n1-insist
      parameters: [""]
    n1-remind:
      name: n1-remind
      parameters: [""]
    n1-repeat:
      name: n1-repeat
      parameters: [""]
    n1-warn:
      name: n1-warn
      parameters: [""]
    pw-another:
      name: pw-another
      parameters: ["text"]
    pw-fail:
      name: pw-fail
      parameters: [""]
    pw-found:
      name: pw-found
      parameters: ["text"]
    pw-misfire:
      name: pw-misfire
      paramaters: ["text"]
    pw-suggest:
      name: pw-suggest
      container: true
      children: ["pw-another", "pw-fail"]
      parameters: ["text"]
    random-once:
      name: random-once
      children: ["ro-choice"]
      container: true
      parameters: ["bareword"]
    return-block:
      name: return-block
      container: true
      parameters: [""]
    return-head:
      name: return-head
      parameters: [""]
    ro-choice:
      name: ro-choice
      parameters: ["|+ text"]
    revisit-here:
      name: revisit-here
    state-delete:
      name: state-delete
      parameters: ["bareword |+ ...bareword"]
    state-load:
      name: state-load
      parameters: ["bareword"]
    state-save:
      name: state-save
      parameters: ["bareword &+ ...bareword"]
    vi-always:
      name: vi-always
      parameters: ["bareword &+ text |+ ...text"]
    vi-always-if:
      name: vi-always-if
      parameters: ["bareword &+ bareword &+ text |+ ...text"]
    vi-ignore:
      name: vi-ignore
      parameters: ["bareword |+ ...bareword"]
    vi-ignore-if:
      name: vi-ignore-if
      parameters: ["bareword &+ ...bareword"]


