sugarcube-2:
  macros:
    add-action:
      name: add-action
    assert-fail:
      name: assert-fail
    assert-true:
      name: assert-true
    arousalbar:
      name: arousalbar
    big-mood:
      name: big-mood
      parameters:
        - "(bareword|var) &+ ( 'ignore'|'TODO'|'vary' )"
        - "(bareword|var) &+ ( 'always'|'assert'|'implies' ) &+ ...text"
    delete-vars:
      name: delete-vars
      parameters: ['bareword |+ ...bareword']
    fade-in:
      name: fade-in
      children: ['next']
      container: true
      parameters: ['|+ bareword']
    get-actions:
      name: get-actions
      parameters: ['']
    n1-patience:
      name: n1-patience
      parameters: ['number &+ number &+ text |+ text |+ text']
    no-trace:
      name: no-trace
      container: true
    optional-action:
      name: optional-action
      parameters: ['text']
    timed-beat:
      name: timed-beat
      container: true
      parameters: ['text |+ text']
    "TOD\x4f":
      name: "TOD\x4f"

