sugarcube-2:
  macros:
    add-action:
      name: add-action
    assert-true:
      name: assert-true
    arousalbar:
      name: arousalbar
    delete-vars:
      name: delete-vars
      parameters: ['text |+ ...text']
    get-actions:
      name: get-actions
      parameters: ['']
    n1-patience:
      name: n1-patience
      parameters: ['number &+ number &+ text |+ text |+ text']
    optional-action:
      name: optional-action
      parameters: ['text']
    timed-beat:
      name: timed-beat
      container: true
      parameters: ['text |+ text']

