sugarcube-2:
  macros:
    add-action:
      name: add-action
    assert-big-mood:
      name: assert-big-mood
      parameters: ['bareword &+ text']
    assert-true:
      name: assert-true
    arousalbar:
      name: arousalbar
    big-mood-todo:
      name: big-mood-todo
      parameters: ['bareword |+ ...bareword']
    delete-vars:
      name: delete-vars
      parameters: ['bareword |+ ...bareword']
    get-actions:
      name: get-actions
      parameters: ['']
    ignore-big-mood:
      name: ignore-big-mood
      parameters: ['bareword |+ ...bareword']
    n1-patience:
      name: n1-patience
      parameters: ['number &+ number &+ text |+ text |+ text']
    optional-action:
      name: optional-action
      parameters: ['text']
    timed-beat:
      name: timed-beat
      container: true
      parameters: ['text |+ text']

