sugarcube-2:
  macros:
    arousalbar:
      name: arousalbar
    delete-vars:
      name: delete-vars
      parameters: 'string |+ ...string'
    flag-debug:
      name: flag-debug
      parameters: 'string |+ ...string'
    n1-patience:
      name: n1-patience
      parameters: 'number |& number |& string |+ string |+ string'
    optional-action:
      name: optional-action
      parameters: 'string'

