sugarcube-2:
  macros:
    arousalbar:
      name: arousalbar
    delete-vars:
      name: delete-vars
      parameters: ['text |+ ...text']
    n1-patience:
      name: n1-patience
      parameters: ['number &+ number &+ text |+ text |+ text']
    optional-action:
      name: optional-action
      parameters: ['text']

